version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "nemesis-facade"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1sdaaapyylmkg"
s3_prefix = "nemesis-facade"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
